### ISSUE TITLE
Failed to create new project

### ISSUE THREAD

**Issue by kidwm** [mhayes/foundation-cli#2]
With bower 1.2.7

```
WMteki-MacBook-Air% foundation new yati
Creating ./yati
      create  yati
remote: Counting objects: 55, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 55 (delta 17), reused 52 (delta 15)
Unpacking objects: 100% (55/55), done.
Installing dependencies with bower...
/Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/foundation-1.0.2/lib/foundation/cli/generator.rb:68:in `read': No such file or directory - /Users/wm/Projects/yati/bower_components/foundation/scss/foundation/_settings.scss (Errno::ENOENT)
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/foundation-1.0.2/lib/foundation/cli/generator.rb:68:in `block in new'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/thor-0.18.1/lib/thor/actions.rb:182:in `block in inside'
    from /Users/wm/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
    from /Users/wm/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/thor-0.18.1/lib/thor/actions.rb:182:in `inside'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/foundation-1.0.2/lib/foundation/cli/generator.rb:65:in `new'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/gems/foundation-1.0.2/bin/foundation:4:in `<top (required)>'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/bin/foundation:23:in `load'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/bin/foundation:23:in `<main>'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `eval'
    from /Users/wm/.rvm/gems/ruby-2.0.0-p195/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kidwm** [comment]
I think it is because that I've changed the path to 'app/components' in my .bowerrc

**Comment by mhayes** [comment]
Meant to close this a while back, the CLI now respects a local `.bowerrc` file if one exists.
